#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""给 sz 项目 6 份种子上传文件补真实内容的 dataUrl。
- .txt 文件 -> base64 的 text/plain dataUrl（企业情报原文）
- .pdf 文件 -> 生成一份内容真实、可在浏览器 iframe 内渲染的最小 PDF
"""
import json, base64, urllib.request, io

SYNC_URL = "https://huixiaozhao-demo-production-21e7.up.railway.app/api/sync"

# ---- 企业情报原文（来自 index.html 随州 AI 扫描数据整理） ----
TXT = {
"企业-国鸿氢能.txt": """国鸿氢能科技（代号：氢驰B）— 企业情报卡
============================================
所属缺口环节：燃料电池电堆
企业类型：燃料电池电堆制造企业
所在区域：广东云浮 / 华南
企业规模：港股上市（02498），2025年H1营收3.8亿，电堆年产能超10万台
技术路线：石墨板电堆，已有多款重卡应用，成本低于金属板约15%

扩张信号（✅ 有效）：
2025年7月公告，与湖北省政府签署战略合作备忘录，明确在武汉城市圈内
布局中部生产基地，计划2026年投产。
信号来源：港交所公告（2025-07-15）+ 湖北省政府官网新闻

补链匹配点：
1. 已明确在湖北布局，随州专汽整车产量可成为配套基地最优落点。
2. 石墨板成本优势契合随州专用车降本需求，性价比高于金属板方案。
3. 战略备忘录已签，政府关系成熟，落地阻力小于从零开始谈判。

待沟通问题：
- 湖北布局的具体选址进展，随州是否在候选名单中
- 石墨板电堆与新楚风49T氢重卡的功率匹配测试情况
- 随州与武汉基地协同配套的供应链方案

综合评级：优先级 5 / 本地化属性 A（必须本地化）
""",
"企业-未势能源.txt": """未势能源 — 企业情报卡
============================================
所属缺口环节：高压储氢系统 / 储氢瓶
企业类型：氢燃料电池核心零部件与储氢系统供应商
所在区域：河北保定（长城汽车旗下）
企业规模：国内商用车储氢系统主力供应商之一，配套多款重卡示范车型
技术路线：35MPa / 70MPa 高压储氢瓶及瓶阀、减压系统，商用车整套储氢方案

补链匹配点：
1. 储氢系统直补随州氢能专用车"储氢瓶与瓶阀"缺口环节。
2. 已配套商用车整车，与新楚风/程力49T氢重卡路线契合。
3. 具备储氢瓶扩产能力，若在随州落地可就近配套整车厂。

待沟通问题：
- 是否有在湖北/中部地区新建储氢瓶产线的计划
- 与随州整车厂的储氢系统联合开发意向
- 落地随州所需的政策与园区配套条件

综合评级：储氢环节重点招引对象 / 本地化属性 A
""",
"企业-亿华通(反例-无信号).txt": """亿华通动力科技（代号：氢驰A）— 企业情报卡【反例·无扩张信号】
============================================
所属缺口环节：燃料电池电堆 / 系统
企业类型：商用车燃料电池系统集成商
所在区域：北京 / 华北
企业规模：上市公司（688339），2024年营收4.2亿，商用车功率段主力
技术路线：金属双极板PEMFC，120-200kW商用车段，客户含宇通/福田/北汽

扩张信号（⚠️ 无效 / 反例）：
目前无明确中部建厂公告。2024年报显示产能利用率不足60%，以华北/西北
市场为主，中部扩张尚无公开计划。
信号来源：公司年报2024 + A股公告（核实截至2026-07）

判定说明：
技术路线虽契合，但【无可查证的扩张/迁移信号】，按"企业推荐严格标准"
不列入优先候选，仅作对照反例保留。若要接触需政府主动招引沟通。

补链匹配点（仅供参考）：
1. 技术路线与新楚风49T氢重卡需求高度契合（商用车功率段）。
2. 直补随州电堆53%最大缺口，一旦落地即锁定程力/新楚风稳定采购。
3. 华北产能过剩（利用率<60%），存在异地扩产动机，但需主动沟通。

综合评级：优先级 3 / 本地化属性 A（当前无信号，暂缓）
""",
}

PDF_TEXT_LINES = [
    "未势能源 - 储氢瓶扩产 - 随州补链 项目材料",
    "",
    "一、项目背景",
    "随州氢能专用车产业在燃料电池电堆与高压储氢系统环节存在明显缺口，",
    "储氢瓶与瓶阀长期依赖外购。未势能源作为国内商用车储氢系统主力供应商，",
    "具备35MPa/70MPa高压储氢瓶及整套储氢方案的量产能力。",
    "",
    "二、扩产与补链方向",
    "拟推动未势能源在随州就近布局储氢瓶产线，直接配套本地专用车整车厂",
    "（新楚风/程力49T氢重卡路线），降低储氢系统整体物流与采购成本。",
    "",
    "三、待确认事项",
    "1. 中部/湖北储氢瓶产线新建计划与选址进展；",
    "2. 与随州整车厂的储氢系统联合开发意向；",
    "3. 落地随州所需的园区洁净厂房条件与政策支持。",
    "",
    "四、综合评级",
    "储氢环节重点招引对象，本地化属性 A（必须本地化）。",
]


def make_pdf(lines):
    """生成一份最小但合规、可在浏览器内直接渲染的 PDF（用 Type0/Identity-H 内嵌？
    过于复杂。这里改用 WinAnsi 无法显示中文——因此改为使用 reportlab 若可用，
    否则退化为把中文转成图片式? 简化：优先 reportlab。"""
    try:
        from reportlab.pdfgen import canvas
        from reportlab.lib.pagesizes import A4
        from reportlab.pdfbase import pdfmetrics
        from reportlab.pdfbase.cidfonts import UnicodeCIDFont
        buf = io.BytesIO()
        c = canvas.Canvas(buf, pagesize=A4)
        pdfmetrics.registerFont(UnicodeCIDFont('STSong-Light'))
        c.setFont('STSong-Light', 14)
        w, h = A4
        y = h - 60
        for ln in lines:
            if ln.strip() == "":
                y -= 12
                continue
            size = 16 if (ln.endswith("项目材料")) else (13 if ln.startswith(("一","二","三","四")) else 11)
            c.setFont('STSong-Light', size)
            c.drawString(50, y, ln)
            y -= size + 8
            if y < 60:
                c.showPage(); c.setFont('STSong-Light', 11); y = h - 60
        c.showPage(); c.save()
        return buf.getvalue(), True
    except Exception as e:
        print("reportlab unavailable:", e)
        return None, False


def main():
    # 拉云端现状
    raw = urllib.request.urlopen(SYNC_URL, timeout=40).read().decode('utf-8')
    d = json.loads(raw)
    ups = d.get('UPLOADS', {}).get('sz', [])
    print("current sz uploads:", len(ups))

    pdf_bytes, ok = make_pdf(PDF_TEXT_LINES)
    pdf_dataurl = None
    if ok:
        pdf_dataurl = "data:application/pdf;base64," + base64.b64encode(pdf_bytes).decode()
        print("pdf generated bytes:", len(pdf_bytes))

    for u in ups:
        name = u.get('name')
        if name in TXT and not u.get('dataUrl'):
            b = TXT[name].encode('utf-8')
            u['dataUrl'] = "data:text/plain;charset=utf-8;base64," + base64.b64encode(b).decode()
            print("filled txt:", name)
        elif name.lower().endswith('.pdf') and pdf_dataurl and not u.get('dataUrl'):
            u['dataUrl'] = pdf_dataurl
            print("filled pdf:", name)

    # 只推送 UPLOADS（POST 合并逻辑会把该字段整体替换）
    payload = json.dumps({"UPLOADS": d.get('UPLOADS', {})}, ensure_ascii=False).encode('utf-8')
    req = urllib.request.Request(SYNC_URL, data=payload, method='POST',
                                 headers={'Content-Type': 'application/json'})
    resp = urllib.request.urlopen(req, timeout=60).read().decode('utf-8')
    print("POST resp:", resp)

    # 回读验证
    raw2 = urllib.request.urlopen(SYNC_URL, timeout=40).read().decode('utf-8')
    d2 = json.loads(raw2)
    for u in d2.get('UPLOADS', {}).get('sz', []):
        print("verify:", u.get('name'), "dataUrl?", bool(u.get('dataUrl')), "len", len(u.get('dataUrl', '')))


if __name__ == "__main__":
    main()
